// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NcpAdminBlazor.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NcpAdminBlazorApiServiceAspNetCoreMyTokenResponse : global::NcpAdminBlazor.Client.Models.FastEndpointsSecurityTokenResponse, IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accessTokenExpiry property</summary>
        public DateTimeOffset? AccessTokenExpiry { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The refreshTokenExpiry property</summary>
        public DateTimeOffset? RefreshTokenExpiry { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NcpAdminBlazor.Client.Models.NcpAdminBlazorApiServiceAspNetCoreMyTokenResponse"/> and sets the default values.
        /// </summary>
        public NcpAdminBlazorApiServiceAspNetCoreMyTokenResponse() : base()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NcpAdminBlazor.Client.Models.NcpAdminBlazorApiServiceAspNetCoreMyTokenResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::NcpAdminBlazor.Client.Models.NcpAdminBlazorApiServiceAspNetCoreMyTokenResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NcpAdminBlazor.Client.Models.NcpAdminBlazorApiServiceAspNetCoreMyTokenResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "accessTokenExpiry", n => { AccessTokenExpiry = n.GetDateTimeOffsetValue(); } },
                { "refreshTokenExpiry", n => { RefreshTokenExpiry = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteDateTimeOffsetValue("accessTokenExpiry", AccessTokenExpiry);
            writer.WriteDateTimeOffsetValue("refreshTokenExpiry", RefreshTokenExpiry);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
