// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NcpAdminBlazor.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NcpAdminBlazorWebEndpointsMenusManagementCreateMenuRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The icon property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Icon { get; set; }
#nullable restore
#else
        public string Icon { get; set; }
#endif
        /// <summary>The isDisabled property</summary>
        public bool? IsDisabled { get; set; }
        /// <summary>The order property</summary>
        public int? Order { get; set; }
        /// <summary>The pageKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PageKey { get; set; }
#nullable restore
#else
        public string PageKey { get; set; }
#endif
        /// <summary>The parentId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentId { get; set; }
#nullable restore
#else
        public string ParentId { get; set; }
#endif
        /// <summary>The path property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The permissionCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PermissionCode { get; set; }
#nullable restore
#else
        public string PermissionCode { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The type property</summary>
        public int? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NcpAdminBlazor.Client.Models.NcpAdminBlazorWebEndpointsMenusManagementCreateMenuRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NcpAdminBlazor.Client.Models.NcpAdminBlazorWebEndpointsMenusManagementCreateMenuRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NcpAdminBlazor.Client.Models.NcpAdminBlazorWebEndpointsMenusManagementCreateMenuRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "icon", n => { Icon = n.GetStringValue(); } },
                { "isDisabled", n => { IsDisabled = n.GetBoolValue(); } },
                { "order", n => { Order = n.GetIntValue(); } },
                { "pageKey", n => { PageKey = n.GetStringValue(); } },
                { "parentId", n => { ParentId = n.GetStringValue(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "permissionCode", n => { PermissionCode = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "type", n => { Type = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("icon", Icon);
            writer.WriteBoolValue("isDisabled", IsDisabled);
            writer.WriteIntValue("order", Order);
            writer.WriteStringValue("pageKey", PageKey);
            writer.WriteStringValue("parentId", ParentId);
            writer.WriteStringValue("path", Path);
            writer.WriteStringValue("permissionCode", PermissionCode);
            writer.WriteStringValue("title", Title);
            writer.WriteIntValue("type", Type);
        }
    }
}
#pragma warning restore CS0618
