// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using NcpAdminBlazor.Client.Api.Menus;
using NcpAdminBlazor.Client.Api.Permissions;
using NcpAdminBlazor.Client.Api.Roles;
using NcpAdminBlazor.Client.Api.User;
using NcpAdminBlazor.Client.Api.Users;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace NcpAdminBlazor.Client.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The menus property</summary>
        public global::NcpAdminBlazor.Client.Api.Menus.MenusRequestBuilder Menus
        {
            get => new global::NcpAdminBlazor.Client.Api.Menus.MenusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The permissions property</summary>
        public global::NcpAdminBlazor.Client.Api.Permissions.PermissionsRequestBuilder Permissions
        {
            get => new global::NcpAdminBlazor.Client.Api.Permissions.PermissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The roles property</summary>
        public global::NcpAdminBlazor.Client.Api.Roles.RolesRequestBuilder Roles
        {
            get => new global::NcpAdminBlazor.Client.Api.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::NcpAdminBlazor.Client.Api.User.UserRequestBuilder User
        {
            get => new global::NcpAdminBlazor.Client.Api.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::NcpAdminBlazor.Client.Api.Users.UsersRequestBuilder Users
        {
            get => new global::NcpAdminBlazor.Client.Api.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NcpAdminBlazor.Client.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NcpAdminBlazor.Client.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
